# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: [self-hosted, my-label]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Set repo secret
        run: echo "$SECRET_TEST_REPO" > key_repo && chmod 600 key_repo
        env:
          SECRET_TEST_REPO: ${{ secrets.SECRET_TEST_REPO }}

      # Runs a set of commands using the runners shell
      - name: Set org secret
        run: echo "$SECRET_TEST_ORG" > key_org && chmod 600 key_org
        env:
          SECRET_TEST_ORG: ${{ secrets.SECRET_TEST_ORG }}

      # Runs a set of commands using the runners shell
      - name: Echo
        run: |
          cat key_repo
          cat key_org
